use_frameworks!

target 'KYSIOSShared_Example' do
  pod 'KYSIOSShared', :path => '../'

  target 'KYSIOSShared_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
